import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='container mx-auto h-screen'>
          <div classname=''>
            <div className=''>Portfolio Example.</div>
          </div>
        </div>
      </main>

      <footer>
      </footer>

    </div>
  )
}
